SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE - (C.DAILY_FEE * (CAST(REPLACE(D.DISCOUNT_RATE, '%', '') AS DECIMAL) / 100))) * 30 AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON 
    C.CAR_TYPE = D.CAR_TYPE
AND D.DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('SUV', '세단')
    AND C.CAR_ID NOT IN (
        SELECT DISTINCT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE 
            H.START_DATE <= '2022-11-30' 
            AND H.END_DATE >= '2022-11-01'
    )
    AND (C.DAILY_FEE - (C.DAILY_FEE * (CAST(REPLACE(D.DISCOUNT_RATE, '%', '') AS DECIMAL) / 100))) * 30
        BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;