SELECT
    I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM
    REST_INFO I
JOIN
    (SELECT  
        FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
     FROM
        REST_INFO
     GROUP BY
        FOOD_TYPE) AS T
ON 
    T.FOOD_TYPE = I.FOOD_TYPE AND
    T.MAX_FAVORITES = I.FAVORITES
ORDER BY
    1 DESC;