SELECT 
    A.CATEGORY, A.PRICE, A.PRODUCT_NAME 
FROM 
    FOOD_PRODUCT A
JOIN 
    (SELECT 
        PRODUCT_NAME, 
        MAX(PRICE) AS MP, 
        CATEGORY 
     FROM FOOD_PRODUCT 
     GROUP BY CATEGORY) B
ON 
    A.PRICE = B.MP AND
    A.CATEGORY = B.CATEGORY
WHERE 
    A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 
    PRICE DESC